server:
  port: 9090
spring:
  application.name: client
  security:
    oauth2:
      client:
        registration:
          test-client-oidc:
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            clientName: test-client-oidc
            provider: custom
        provider:
          custom:
            issuer-uri: http://localhost:8080
logging:
  level:
    org:
      springframework:
        security: trace